### ISSUE TITLE
@archisha69 has skill issue (fixed accidentally wrong ping)

### ISSUE THREAD

**Issue by nickoncrack** [XyrenTheCoder/simple-calculator#1]
original code by stackoverflow, geeksforgeeks and some other websites*

**Comment by XyrenTheCoder** [comment]
we dont do that here

**Comment by nickoncrack** [comment]
but the code isnt by @thatOneArchUser

**Comment by XyrenTheCoder** [comment]
cap

**Comment by nickoncrack** [comment]
no cap

**Comment by nickoncrack** [comment]
@thatOneArchUser  copied it

**Comment by XyrenTheCoder** [comment]
no

**Comment by nickoncrack** [comment]
> 

but he really did
source: trust me bro

**Comment by XyrenTheCoder** [comment]
> > 
> 
> but he really did source: trust me bro

capppppp
